### ISSUE TITLE
hardhat.config.ts (bugs)

### ISSUE THREAD

**Issue by Yous18** [aave/gho-core#285]
The fact function is not defined, which will cause a NameError to be raised when the code is executed.

The code attempts to pass an argument to the print function which is not a string, which will raise a TypeError.

The code doesn't return a value from the fact function, which may lead to unexpected results when the function is called elsewhere in the code.

**Comment by miguelmtzinf** [comment]
Which function are you referring to @Yous18 ? What error message are you getting?
Could you provide a detailed list of the steps you followed to reproduce the issue?
