### ISSUE TITLE
balance not detected

### ISSUE THREAD

**Issue by Jati199** [aave/gho-core#286]
hi teams
Previously I had claimed the AAVE faucet and it was successful with the appearance of a green sentence as a notification. but when I'm in the aave details menu on the market. **there my balance is not visible**. I have refreshed several times with the same result.
there I tried my luck to click on the avee faucet on the small menu and it worked then after a few moments my balance appeared there.
during the testnet process I did not experience any problems. maybe it was just a small obstacle, but it will be a big problem if you leave it to the mainnet
and I haven't been able to beat NFT
![GHO AVEE (1)](https://user-images.githubusercontent.com/89678384/218274086-3ecff972-5681-4f82-b47a-ae01ce53aaf6.jpg)
![GHO AVEE (2)](https://user-images.githubusercontent.com/89678384/218274090-4e882c3c-8018-4e02-ace3-8887b9eda27f.jpg)
![photo_2023-02-12_01-07-53](https://user-images.githubusercontent.com/89678384/218274265-aeb60e3c-52e0-486c-8ecd-da23912418a5.jpg)

**Comment by miguelmtzinf** [comment]
Thanks @Jati199 
This is the code repository for GHO smart contracts. I suggest you to get in contact with the team via [gho-security@aave.com](mailto:gho-security@aave.com)
