### ISSUE TITLE
ETH borrowing bug

### ISSUE THREAD

**Issue by crackyto** [aave/gho-core#288]
When I make an ETH loan with the address 0x3eD08A777a1B087F8bc73Ca94B14Ba64aB8368E2 it works with the application in English, however when I do the test with the page in French I have the error message attached.
Otherwise what a treat to test AAVE

![AAVE FR](https://user-images.githubusercontent.com/110041791/218526497-6027ee36-27d0-4302-9fcb-f5333b29913d.png)
![AAVE EN](https://user-images.githubusercontent.com/110041791/218526548-521b8812-68aa-4a37-a3b6-6479178ad34a.png)

**Comment by foodaka** [comment]
As per the guidelines all bugs should be reported to gho-security@aave.com
