### ISSUE TITLE
Misc items in GhoDiscountRateStrategy for readiabilty

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/gho-core#300]
Consider specifying this value as "0.2e4" for readability.

https://github.com/aave/gho-core/blob/7ae72de8fdbb4dbcf27bd0814866f1c2632b859e/src/contracts/facilitators/aave/interestStrategy/GhoDiscountRateStrategy.sol#L25

Brackets are redundant.
https://github.com/aave/gho-core/blob/7ae72de8fdbb4dbcf27bd0814866f1c2632b859e/src/contracts/facilitators/aave/interestStrategy/GhoDiscountRateStrategy.sol#L51

**Comment by Zer0dot** [comment]
Disagree on this. How is 0.2e4 more readable than 2000?

Nevertheless, it's such a small change that it doesn't matter to me.
