### ISSUE TITLE
fix: allow gho steward param change in both directions

### ISSUE THREAD

**Issue by brotherlymite** [aave/gho-core#401]
For more flexibility and feedback from riskCouncil, I think the [GhoStewardV2](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol) should allow changing the [facilitatorBucketCapacity](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol#L114), [ghoBorrowCap](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol#L131), [gsmExposureCap](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol#L183), [gsmBuySellFees](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol#L199) in both the directions (increase / decrease).

Should be quite straightforward using the `_isDifferenceLowerThanMax` method instead of `_isIncreaseLowerThanMax`.

Also this [comment](https://github.com/bgd-labs/gho-core/blob/main/src/contracts/misc/GhoStewardV2.sol#L23), should be patched from `PoolAdmin` to `RiskAdmin` imo and the tests should be fixed as the `RiskAdmin` role should be sufficient.

**Comment by miguelmtzinf** [comment]
Thanks @brotherlymite for raising this issue.

Steward design and capabilities are decided by governance discussion. #402 updates the contract based on the last discussion of the gov thread.
The design and capabilities of the steward are determined through governance discussions. PR#402 modifies the contract in line with the [latest discussions from the governance thread](https://governance.aave.com/t/arfc-gho-stewards/16466/11).

#402 fixes the nastpec docs of the contract, so closing this issue now.
