### ISSUE TITLE
GHO Steward Cross-Chain Support

### ISSUE THREAD

**Issue by CheyenneAtapour** [aave/gho-core#415]
With GHO launched on Arbitrum, it is desirable to extend the GhoSteward to cover additional controls, allowing the DAO to react and make changes in an agile way.

It is desired to have the following additional controls:

On Ethereum:
* Ability to change bridge limit
* Ability to change CCIP token pool rate limit

On Arbitrum:
* Ability to change CCIP token pool rate limit
* Ability to change Facilitator bucket capacity of CCIP

**Comment by miguelmtzinf** [comment]
For reference: https://governance.aave.com/t/arfc-extend-gho-stewards-to-arbitrum/18298
